### ISSUE TITLE
Suggestion: use mdfind instead of find

### ISSUE THREAD

**Issue by davedelong** [klaaspieter/chxcode#1]
`find` is a great way to find something by its name, but not everyone names their Xcodes staring with `Xcode-*`. Additionally, the use of `-maxdepth 1` means you won't find Xcodes inside other folders (perhaps an "Xcodes" folder?)

As an alternative, the `mdfind` command can find the paths to Xcodes based on their *bundle identifier*, which means it doesn't matter what they're called; it'll find them.

The command for that would be:

```
mdfind -onlyin "$APPLICATIONS" "kMDItemCFBundleIdentifier='com.apple.dt.Xcode'" | sort
```

Where your `find` command finds none of my Xcodes, using `mdfind` finds all 15 of them. :)

**Comment by klaaspieter** [comment]
Thanks, that's a good suggestion. I built chxcode to scratch my own itch. Currently it primarily supports Xcodes installed by [xcode-install]. Anything else it finds is just a happy coincidence.

That said, I would love to make it more robust and looked into using `mdfind`. So far I wasn't able to make the tests work. Partially because `/tmp` is not indexed by Spotlight, but more importantly I don't seem to be able to write Spotlight attributes on the fake Xcodes created by the tests. The internet suggests `xattr -w com.apple.metadata:kMDItemFSName com.apple.dt.Xcode "[PATH /TO/Xcode.app]"` should work, but it looks like that changed in a recent OS update. `xattr -l /Applications/Xcode.app` doesn't show any attributes.

[xcode-install]: https://github.com/KrauseFx/xcode-install

This is a good nerd-snipe 👍

**Comment by klaaspieter** [comment]
Update: after much trial and error it looks like using `mdfind` is possible. To make it work for the test suite we need to move a fake app bundle into place that has an `Info.plist` with `CFBundleIdentifier` and `CFBundleShortVersionString` set. 

I initially tried to `cp -Rp` a `Fake.app` into `./test/tmp`, but `mdls` initially returns `(null)` for most values when using that approach.  Eventually `mdls` will return the expected values but waiting on it requires `sleep` and that seems wrong.

I'm going to try another approach where we have a pre-defined directory with fakes already in place. I dislike this approach because it introduces a [Mystery Guest] into the test suite. Compared with `sleep` it seems the lesser of two evils.

[Mystery Guest]: http://xunitpatterns.com/Obscure%20Test.html#Mystery%20Guest
