### ISSUE TITLE
Add to homebrew

### ISSUE THREAD

**Issue by AndrewSB** [klaaspieter/chxcode#4]
#feature-request

I'd love to be able to install this through a package manager

**Comment by klaaspieter** [comment]
Thanks. I had set up my [homebrew tap](https://github.com/klaaspieter/homebrew-formula) a while ago, but forgot to add it to the README. 

Fixed with 9301133a2a05f40ed6b398379ec5bbc5a07dcf6b.

I would love for this be in homebrew core, but from https://docs.brew.sh/Acceptable-Formulae. 

> We frown on authors submitting their own work unless it is very popular.

I also vageuely recall a project needing 100 stars.

**Comment by AndrewSB** [comment]
you've got a star from me, I'll use your tap for now
